# Generated by Django 4.1.4 on 2023-06-09 16:09

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0007_cartitem_total_price'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CartItem',
            new_name='Cart',
        ),
        migrations.RenameModel(
            old_name='Menu',
            new_name='Product',
        ),
    ]
