# Generated by Django 4.1.4 on 2023-06-09 16:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0008_rename_cartitem_cart_rename_menu_product'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cart',
            new_name='CartItem',
        ),
        migrations.RenameModel(
            old_name='Product',
            new_name='Menu',
        ),
    ]
